#!/usr/bin/expect -f

set timeout 20
set old_password "c98fcaa6f317653338e1617cb0"
set new_password "NewSecurePassword2025!"

spawn ssh -o StrictHostKeyChecking=no root@46.101.189.137

expect "Password:"
send "$old_password\r"

expect "You are required to change your password immediately"
expect "Password:"
send "$old_password\r"

expect "New password:"
send "$new_password\r"

expect "Retype new password:"
send "$new_password\r"

expect "$ "
send "exit\r"

expect eof