name: "🚀 Simple Deploy"

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: "Deploy"
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      
      - name: Deploy
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY || 'LS0tLS1CRUdJTiBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0KYjNCbGJuTnphQzFyWlhrdGRqRUFBQUFBQkc1dmJtVUFBQUFFYm05dVpRQUFBQUFBQUFBQkFBQUFNd0FBQUF0emMyZ3RaVwpReU5UVXhPUUFBQUNCdzlzRE4vRktmWE9vNThvNERjWnQrMm05WHJiV0I4QTQ1bHJiZHhScEdKQUFBQUpoL3lzbS9mOHJKCnZ3QUFBQXR6YzJndFpXUXlOVFV4T1FBQUFDQnc5c0ROL0ZLZlhPbzU4bzREY1p0KzJtOVhyYldCOEE0NWxyYmR4UnBHSkEKQUFBRUJqSnpjWVpSQ21MZHJxZFVJRTRKQWRyeXYvaDlkOW9LSTZZS3lSa1haV2VYRDJ3TTM4VXA5YzZqbnlqZ054bTM3YQpiMWV0dFlId0RqbVd0dDNGR2tZa0FBQUFGV2RwZEdoMVlpMWhZM1JwYjI1ekxXUmxjR3h2ZVE9PQotLS0tLUVORCBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0K' }}
        run: |
          mkdir -p ~/.ssh
          echo "$DEPLOY_KEY" | base64 -d > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H 138.197.187.49 >> ~/.ssh/known_hosts 2>/dev/null || true
          
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_ed25519 dev@138.197.187.49 << 'ENDSSH'
          set -e
          
          echo "Setting up project directory..."
          if [ ! -d "/opt/obsidian-comments" ]; then
            sudo mkdir -p /opt/obsidian-comments
            sudo chown -R dev:dev /opt/obsidian-comments
          fi
          
          # Fix any permission issues
          sudo chown -R dev:dev /opt/obsidian-comments || true
          
          cd /opt/obsidian-comments
          
          echo "Pulling latest code..."
          if [ ! -d ".git" ]; then
            git init
            git remote add origin https://github.com/pangeafate/ObsidianComments.git
            git fetch origin main
            git checkout -b main origin/main
          else
            git fetch origin main
            git reset --hard origin/main
          fi
          
          echo "Stopping existing services..."
          docker stop $(docker ps -q) 2>/dev/null || true
          docker rm $(docker ps -aq) 2>/dev/null || true
          
          echo "Starting PostgreSQL and Redis..."
          docker run -d --name postgres --network obsidian-comments_obsidian_network \
            -e POSTGRES_DB=obsidian_comments \
            -e POSTGRES_USER=postgres \
            -e POSTGRES_PASSWORD=obsidian_prod_db_2025_secure \
            postgres:15
          
          docker run -d --name redis --network obsidian-comments_obsidian_network \
            redis:7-alpine
          
          echo "Waiting for database to be ready..."
          sleep 15
          
          echo "Starting application services..."
          docker run -d --name backend --network obsidian-comments_obsidian_network \
            --env-file .env.production \
            ghcr.io/pangeafate/obsidiancomments-backend:${GITHUB_SHA}
          
          docker run -d --name hocuspocus --network obsidian-comments_obsidian_network \
            --env-file .env.production \
            -e PORT=8082 \
            ghcr.io/pangeafate/obsidiancomments-hocuspocus:${GITHUB_SHA}
          
          docker run -d --name frontend --network obsidian-comments_obsidian_network \
            ghcr.io/pangeafate/obsidiancomments-frontend:${GITHUB_SHA}
          
          echo "Starting nginx..."
          docker run -d --name nginx --network obsidian-comments_obsidian_network \
            -p 80:80 -p 443:443 \
            -v /opt/obsidian-comments/nginx.conf:/etc/nginx/nginx.conf \
            -v /etc/nginx/ssl:/etc/nginx/ssl \
            nginx:alpine
          
          echo "Deployment complete!"
          docker ps
          ENDSSH